version: '3.7'
services:
    postgres:
        image: postgres:12.5   #update version if necessary
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "9432:5432"   #set port           

    webserver:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=y   #set n if examples doesn't need
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./airflow:/usr/local/airflow   #set your volume
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
            - "5555:5555"
            - "8793:8793"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3